### ISSUE TITLE
How can we change status bar icons color?

### ISSUE THREAD

**Issue by Slake07** [android/user-interface-samples#108]
I want to change status bar icons color from light to dark or dark to light based on the selected theme. How can I achieve that?

**Comment by nickbutcher** [comment]
Set the [windowLightStatusBar](https://developer.android.com/reference/android/R.attr.html#windowLightStatusBar) theme attribute or call [View.setSystemUiVisibility](https://developer.android.com/reference/android/view/View.html#setSystemUiVisibility(int)) passing [SYSTEM_UI_FLAG_LIGHT_STATUS_BAR](https://developer.android.com/reference/android/view/View.html#SYSTEM_UI_FLAG_LIGHT_STATUS_BAR)
