### ISSUE TITLE
Dark Theme: Elevation Making No Difference in View Appearance

### ISSUE THREAD

**Issue by CodyEddings** [android/user-interface-samples#150]
While trying out the Dark Theme sample I tried to manipulate a CardView's perceived elevation by changing the elevation value in xml. The official [Material.io guide](https://material.io/design/color/dark-theme.html#properties) on Dark Theme indicates that a white tint overlay is supposed to be faded in at various opacity as the elevation increases, giving views in Dark Theme a brightening or "closer to the surface" effect.

I added a card layout to the MainActivity of the DarkThemeApplication and there's no visual difference between 18dp of elevation and 1dp. What am I doing wrong? Am I supposed to implement this elevation effect with a white overlay manually?

![1dp Card Elevation](https://user-images.githubusercontent.com/17996938/77979020-80a13000-72d1-11ea-8dbc-c5601934b0b9.png)
![18dp Card Elevation](https://user-images.githubusercontent.com/17996938/77979026-83038a00-72d1-11ea-83bc-1188b84251c5.png)

**Comment by chrisbanes** [comment]
Can you post the code you are using to increase the elevation?

**Comment by CodyEddings** [comment]
Sure thing. Here's the xml layout for the activity screenshots above. The cardView with id `testCard` is the view that receives the elevation attribute (and ignores it). My toolbar also has an elevation value that doesn't seem to change anything either, like the cardView.

`<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <androidx.appcompat.widget.Toolbar
        style="@style/Widget.MaterialComponents.Toolbar.Primary"
        android:id="@+id/toolbar"
        android:layout_width="0dp"
        android:layout_height="?android:actionBarSize"
        android:elevation="@dimen/toolbar_elevation"
        android:title="@string/app_name"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <FrameLayout
        android:id="@+id/fragment_layout"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:background="attr/colorSurface"
        app:layout_constraintBottom_toTopOf="@+id/navigation"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/toolbar" />

    <androidx.cardview.widget.CardView
        android:id="@+id/testCard"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="4dp"
        android:elevation="1dp"
        app:cardCornerRadius="4dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/toolbar">

        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <ImageView
                android:id="@+id/testImg"
                android:layout_width="100dp"
                android:layout_height="100dp"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

            <TextView
                android:id="@+id/fiveCoinsLabel"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Lorem Ipsum"
                android:textColor="?android:attr/textColorPrimary"
                app:layout_constraintBottom_toTopOf="@+id/testText"
                app:layout_constraintEnd_toStartOf="@id/testButton"
                app:layout_constraintStart_toEndOf="@id/testImg"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintVertical_chainStyle="packed" />

            <TextView
                android:id="@+id/testText"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textSize="16sp"
                android:textStyle="italic"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toStartOf="@id/testButton"
                app:layout_constraintStart_toEndOf="@id/testImg"
                app:layout_constraintTop_toBottomOf="@+id/fiveCoinsLabel" />

            <Button
                android:id="@+id/testButton"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_margin="16dp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintTop_toTopOf="parent" />
        </androidx.constraintlayout.widget.ConstraintLayout>
    </androidx.cardview.widget.CardView>

    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/navigation"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        app:itemBackground="?attr/colorSurface"
        app:itemIconTint="@drawable/bottom_nav_item_background"
        app:itemTextColor="?attr/colorOnBackground"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:menu="@menu/navigation" />

</androidx.constraintlayout.widget.ConstraintLayout>`

**Comment by chrisbanes** [comment]
For CardView, you should be using [`MaterialCardView`](https://developer.android.com/reference/com/google/android/material/card/MaterialCardView), since that is where the overlay logic lives.

**Comment by CodyEddings** [comment]
Interesting, good to know. Is there a Material version of the toolbar we're supposed to use as well?

Anways though, after switching the cardView over to the Material lib's version it still seems like elevation isn't changing the card's overlay properly.

`    <com.google.android.material.card.MaterialCardView
        android:id="@+id/testCard"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="4dp"
        android:elevation="18dp"
        app:cardCornerRadius="4dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/toolbar">`

1dp:
![Material Card 1dp Elevation](https://user-images.githubusercontent.com/17996938/78260553-16a0aa80-74cc-11ea-9586-3180ae3ba6c3.png)

18dp:
![Material Card 18dp Elevation](https://user-images.githubusercontent.com/17996938/78260579-1d2f2200-74cc-11ea-83cd-09bba5255b0a.png)

**Comment by chrisbanes** [comment]
This is what you need for MaterialCardView

```
<com.google.android.material.card.MaterialCardView
    app:cardElevation="18dp" />
```

**Comment by CodyEddings** [comment]
Awesome, it works! Much appreciated.

Is there an equivalent I attribute I should be using to manipulate elevation of Toolbars, Buttons, etc? For example, I see there's a `<com.google.android.material.appbar.MaterialToolbar>` layout but it doesn't have something like a `toolbarElevation` attribute.

**Comment by chrisbanes** [comment]
Only `MaterialCardView` has a special elevation attribute (`CardView` does too), which allows it support elevation pre-Lollipop. It seems that only the compat attribute is hooked up to the overlay logic. 

/cc @ricknout

**Comment by ricknout** [comment]
Yep, `app:cardElevation` is a special case for `MaterialCardView`. Most/all of the other MDC widgets (including `MaterialToolbar`) rely on the `android:elevation` attr which is API 21+, hence dark theme elevation overlays likely won't work by default before Lollipop. Please file a [bug](https://github.com/material-components/material-components-android/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BComponent+name%5D+Short+description+of+issue) on GitHub.

In the meantime, you can get around this by doing it programmatically:
```
(materialToolbar.background as MaterialShapeDrawable).elevation
    = resources.getDimension(R.dimen.elevation)
```
which incidentally also backports the shadow rendering.

**Comment by adrian110288** [comment]
@chrisbanes I have recently noticed strange behavior of `MaterialCardView`; while working on Dark mode the card background gets brighter when I add `cardElevation`. Do you have tips for how to prevent that?

**Comment by adrian110288** [comment]
@ricknout that explains! I am guilty of neglecting the design guidelines! Thanks alot

**Comment by laurencatgreen** [comment]
Elevation for dark theme should be white, since for light it is black, this makes sense as colors invert for dark theme. 

Obviously it would need to be subtle but I don't like this solution of adjusting the card background. Doesn't look right :/
