### ISSUE TITLE
Can't find Bubbles sample

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/user-interface-samples#174]
Says it's available here:
https://youtu.be/fnkFOhA7FC4?list=PLWz5rJ2EKKc9hqKx4qZWolQxy59Bt20t_&t=525

**Comment by AndroidDeveloperLB** [comment]
Seems it's not as the video says. And that it's "People". Am I write?

Maybe Google should update one of those...

**Comment by Harshsidana** [comment]
I was also searching for the same. Couldn't find one.

**Comment by yaraki** [comment]
It's here
https://github.com/android/user-interface-samples/tree/master/People

**Comment by AndroidDeveloperLB** [comment]
@yaraki That's what I wrote...

**Comment by amardeshbd** [comment]
In the video it was assuming it would be called `Bubbles`. But I presume it's interchangeably called People or Bubble.

**Comment by alabiaga** [comment]
@amardeshbd closing. Thanks for calling out but as you know there is always a shuffling of code, directory names and etc..
