### ISSUE TITLE
People: Bubbles link needs to be updated

### ISSUE THREAD

**Issue by alabiaga** [android/user-interface-samples#177]
Bubbles link needs to be updated as it references MessagingStyle notifications as opposed to proper documentation on Bubbles integration in R.

![bubbles-link](https://user-images.githubusercontent.com/494160/85181491-0fc83f00-b254-11ea-8ce1-242886c709bd.png)

This doc is in the progress and I'll update the README once it's done.

**Comment by alabiaga** [comment]
pls assign this to me @yaraki

**Comment by alabiaga** [comment]
@yaraki Also given how much easier it is to update the README, I would like to update the Bubbles readme to include a small sample of how to surface bubbles in R, until the documentation in developer.android.com is updated.

**Comment by yaraki** [comment]
Fixed in #180
