### ISSUE TITLE
Derivative channel image broken in People FAQ

### ISSUE THREAD

**Issue by alabiaga** [android/user-interface-samples#195]
cc/ @yaraki 

Yuichi, can you please upload the attached image to https://github.com/android/user-interface-samples/upload/master/People/screenshots. I thought I included the image in the PR for the FAQ changes but perhaps not having push rights prevented me from doing so. Thanks

![derivative-channel](https://user-images.githubusercontent.com/494160/91854425-b906ba80-ec31-11ea-952f-6626a91b27e0.png)

**Comment by yaraki** [comment]
The image was uploaded.

**Comment by alabiaga** [comment]
thanks Yuichi
