### ISSUE TITLE
WindowInsetsAnimation message holder translates higher than keyboard height

### ISSUE THREAD

**Issue by tinder-levonpetrosyan** [android/user-interface-samples#222]
Hi @chrisbanes, using any other view instead of  `recyclerview` results in moving the message holder far higher than the keyboard height

https://user-images.githubusercontent.com/56700569/109694728-fc3dd980-7b3f-11eb-8570-fbae2a77ab25.mp4

**Comment by chrisbanes** [comment]
Looks to me like you're using `layout_weight=1` or similar, which won't really work here.

**Comment by tinder-levonpetrosyan** [comment]
I have a placeholder (full height, from message holder to toolbar) instead of a recycler view before the first message is sent and opening up the keyboard leads to similar behavior as it is in the example. Any solution for that?

**Comment by chrisbanes** [comment]
Stepping back: would you mind pseudo-coding/sketching out the layout? If you'd prefer to chat over email, feel free to email me: <username> at google.com

**Comment by tinder-levonpetrosyan** [comment]
You can check an example here: https://github.com/tinder-levonpetrosyan/user-interface-samples/commits/main

I want to achieve step one for now (#1: Reacting to the IME coming on/off screen), if I got things right, we don't need `InsetsAnimationLinearLayout` to have at the root of the layout, so removed that from the sample.
