### ISSUE TITLE
Can't get the glance-widget module in the glance branch to build

### ISSUE THREAD

**Issue by tberghuis** [android/user-interface-samples#306]
`e: C:\Users\tom\Desktop\myprojects\android\CryptoPriceWidget-reference\user-interface-samples\AppWidget\glance-widget\src\main\java\com\example\android\glancewidget\FirstGlanceWidget.kt: (24, 31): Unresolved reference: actionLaunchActivity`

**Comment by Lotus-Flower** [comment]
@tberghuis It looks like this has been changed to ```androidx.glance.action.actionStartActivity```
